package com.feduwacomm.mapper;

import com.feduwacomm.entity.InitialModel;
import org.apache.ibatis.annotations.*;

import java.util.List;

/**
 * 初始模型数据访问层
 */
@Mapper
public interface InitialModelMapper {

    /**
     * 插入初始模型记录
     */
    @Insert("""
        INSERT INTO initial_models (
            id, task_id, model_type, generation_method, model_size, architecture_params, metadata,
            model_data, description, labels, random_seed, parameters_count, checksum,
            storage_path, binding_status, binding_mode, binding_auto_generated,
            bound_at, bound_by, unbound_at, unbound_by,
            auto_generated, status, created_at, created_by, updated_at, updated_by
        ) VALUES (
            #{id}, #{taskId}, #{modelType}, #{generationMethod}, #{modelSize}, #{architectureParams}, #{metadata},
            #{modelData}, #{description}, #{labels}, #{randomSeed}, #{parametersCount}, #{checksum},
            #{storagePath}, #{bindingStatus}, #{bindingMode}, #{bindingAutoGenerated},
            #{boundAt}, #{boundBy}, #{unboundAt}, #{unboundBy},
            #{autoGenerated}, #{status}, #{createdAt}, #{createdBy}, #{updatedAt}, #{updatedBy}
        )
        """)
    int insertInitialModel(InitialModel initialModel);

    /**
     * 根据ID查询初始模型
     */
    @Select("SELECT * FROM initial_models WHERE id = #{id}")
    InitialModel selectById(String id);

    /**
     * 查询全部初始模型（按创建时间倒序）
     */
    @Select("SELECT * FROM initial_models ORDER BY created_at DESC")
    List<InitialModel> selectAll();

    /**
     * 根据任务ID查询当前绑定的初始模型
     */
    @Select("""
        SELECT * FROM initial_models
        WHERE task_id = #{taskId}
        LIMIT 1
        """)
    InitialModel selectByTaskId(String taskId);

    /**
     * 根据状态查询初始模型列表
     */
    @Select("SELECT * FROM initial_models WHERE status = #{status} ORDER BY created_at DESC")
    List<InitialModel> selectByStatus(String status);

    /**
     * 更新模型状态
     */
    @Update("""
        UPDATE initial_models
        SET status = #{status},
            updated_at = NOW(),
            updated_by = #{updatedBy}
        WHERE id = #{id}
        """)
    int updateStatus(@Param("id") String id,
                     @Param("status") String status,
                     @Param("updatedBy") String updatedBy);

    /**
     * 更新模型数据与相关元信息
     */
    @Update("""
        UPDATE initial_models
        SET model_data = #{modelData},
            model_size = #{modelSize},
            metadata = #{metadata},
            labels = #{labels},
            description = #{description},
            random_seed = #{randomSeed},
            parameters_count = #{parametersCount},
            checksum = #{checksum},
            storage_path = #{storagePath},
            status = #{status},
            updated_at = NOW(),
            updated_by = #{updatedBy}
        WHERE id = #{id}
        """)
    int updateModelContent(@Param("id") String id,
                           @Param("modelData") String modelData,
                           @Param("modelSize") Long modelSize,
                           @Param("metadata") String metadata,
                           @Param("labels") String labels,
                           @Param("description") String description,
                           @Param("randomSeed") Integer randomSeed,
                           @Param("parametersCount") Integer parametersCount,
                           @Param("checksum") String checksum,
                           @Param("storagePath") String storagePath,
                           @Param("status") String status,
                           @Param("updatedBy") String updatedBy);

    /**
     * 绑定模型到指定任务
     */
    @Update("""
        UPDATE initial_models
        SET task_id = #{taskId},
            binding_status = #{bindingStatus},
            binding_mode = #{bindingMode},
            binding_auto_generated = #{autoGenerated},
            bound_at = NOW(),
            bound_by = #{operatorId},
            unbound_at = NULL,
            unbound_by = NULL,
            updated_at = NOW(),
            updated_by = #{operatorId}
        WHERE id = #{modelId}
        """)
    int bindModelToTask(@Param("modelId") String modelId,
                        @Param("taskId") String taskId,
                        @Param("bindingStatus") String bindingStatus,
                        @Param("bindingMode") String bindingMode,
                        @Param("autoGenerated") boolean autoGenerated,
                        @Param("operatorId") String operatorId);

    /**
     * 解绑任务与模型
     */
    @Update("""
        UPDATE initial_models
        SET task_id = NULL,
            binding_status = #{bindingStatus},
            binding_mode = NULL,
            binding_auto_generated = 0,
            bound_at = NULL,
            bound_by = NULL,
            unbound_at = NOW(),
            unbound_by = #{operatorId},
            updated_at = NOW(),
            updated_by = #{operatorId}
        WHERE id = #{modelId}
          AND task_id = #{taskId}
        """)
    int unbindModelFromTask(@Param("modelId") String modelId,
                            @Param("taskId") String taskId,
                            @Param("bindingStatus") String bindingStatus,
                            @Param("operatorId") String operatorId);

    /**
     * 删除初始模型记录
     */
    @Delete("DELETE FROM initial_models WHERE id = #{id}")
    int deleteById(String id);

    /**
     * 查询待清理的模型(状态为FAILED且创建时间超过指定天数)
     */
    @Select("""
        SELECT * FROM initial_models
        WHERE status = 'FAILED'
          AND created_at < DATE_SUB(NOW(), INTERVAL #{days} DAY)
        """)
    List<InitialModel> selectFailedModelsOlderThan(@Param("days") int days);
}
