package com.feduwacomm.service;

import com.feduwacomm.model.dto.initial.InitialModelDistributeRequest;
import com.feduwacomm.model.dto.initial.InitialModelGenerateRequest;
import com.feduwacomm.model.dto.initial.InitialModelUploadRequest;
import com.feduwacomm.model.vo.initial.InitialModelBindingVO;
import com.feduwacomm.model.vo.initial.InitialModelDownloadVO;
import com.feduwacomm.model.vo.initial.InitialModelDetailVO;
import com.feduwacomm.vo.InitialModelInfoVO;

import java.util.List;

/**
 * 初始模型管理服务
 */
public interface InitialModelGenerationService {

    /**
     * 自动生成初始模型
     *
     * @param request   生成请求
     * @param createdBy 创建者
     * @return 模型详情
     */
    InitialModelDetailVO generateInitialModel(InitialModelGenerateRequest request, String createdBy);

    /**
     * 上传自定义初始模型（元数据 + 文件已入库场景）
     *
     * @param request   上传请求
     * @param filePath  文件路径
     * @param createdBy 上传者
     * @return 模型详情
     */
    InitialModelDetailVO uploadCustomModel(InitialModelUploadRequest request, String filePath, String createdBy);

    /**
     * 分发初始模型
     *
     * @param taskId 任务ID
     * @param request 分发请求
     * @param operatorId 操作人
     * @return 分发后最新的模型详情
     */
    InitialModelDetailVO distributeInitialModel(String taskId, InitialModelDistributeRequest request, String operatorId);

    /**
     * 查询模型详情
     *
     * @param modelId           模型ID
     * @param includeParameters 是否包含模型参数
     * @return 模型详情
     */
    InitialModelDetailVO getModelDetail(String modelId, boolean includeParameters);

    /**
     * 查询模型绑定记录
     *
     * @param modelId 模型ID
     * @return 绑定记录
     */
    List<InitialModelBindingVO> getModelBindings(String modelId);

    /**
     * 查询任务当前绑定的初始模型
     *
     * @param taskId 任务ID
     * @return 绑定信息，未绑定返回 null
     */
    InitialModelBindingVO getTaskBinding(String taskId);

    /**
     * 绑定初始模型到任务
     *
     * @param modelId       模型ID
     * @param taskId        任务ID
     * @param mode          绑定模式（AUTO/CUSTOM）
     * @param autoGenerated 是否由AUTO模式自动生成
     * @param operatorId    操作人
     * @return 生效的绑定记录
     */
    InitialModelBindingVO bindModelToTask(String modelId,
                                          String taskId,
                                          String mode,
                                          boolean autoGenerated,
                                          String operatorId);

    /**
     * 解绑任务和模型
     *
     * @param modelId    模型ID
     * @param taskId     任务ID
     * @param operatorId 操作人
     */
    void unbindModelFromTask(String modelId, String taskId, String operatorId);

    /**
     * 获取模型列表
     *
     * @param status 状态过滤（可选）
     * @return 模型列表
     */
    List<InitialModelInfoVO> listModels(String status);

    /**
     * 删除模型（同时清理绑定记录）
     *
     * @param modelId   模型ID
     * @param operatorId 操作人
     * @return 是否删除成功
     */
    boolean deleteModel(String modelId, String operatorId);

    /**
     * 校验模型完整性
     *
     * @param modelId 模型ID
     * @return 是否校验通过
     */
    boolean validateModelIntegrity(String modelId);

    /**
     * 获取模型生成统计信息
     *
     * @return 统计数据
     */
    InitialModelInfoVO.ModelGenerationStats getGenerationStats();

    /**
     * 对失败的目标虚拟机重新执行初始模型分发。
     *
     * @param modelId 模型ID
     * @param taskId 任务ID
     * @param targetVmIds 需要重试的虚拟机ID列表
     * @param orchestrationId 编排ID（可选）
     * @param attempt 当前重试次数
     */
    void retryInitialModelDistribution(String modelId,
                                       String taskId,
                                       java.util.List<String> targetVmIds,
                                       String orchestrationId,
                                       int attempt);

    /**
     * 预处理初始模型下载载荷，支持存储文件或内存内容。
     *
     * @param modelId 模型ID
     * @return 下载载荷
     */
    InitialModelDownloadVO prepareModelDownload(String modelId);
}
