package com.feduwacomm.entity;

import com.feduwacomm.enums.GenerationMethod;
import com.feduwacomm.enums.InitialModelBindingStatus;
import com.feduwacomm.enums.InitialModelStatus;
import com.feduwacomm.enums.ModelType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 初始模型实体类 (v1.5)
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InitialModel {

    /**
     * 初始模型唯一标识(32位UUID)
     */
    private String id;

    /**
     * 关联任务ID(32位UUID)，未绑定时为空
     */
    private String taskId;

    /**
     * 模型类型
     */
    private ModelType modelType;

    /**
     * 生成方式: AUTO-自动生成, CUSTOM-自定义上传
     */
    private GenerationMethod generationMethod;

    /**
     * 模型大小(字节)
     */
    private Long modelSize;

    /**
     * 架构参数(JSON格式)
     */
    private String architectureParams;

    /**
     * 元数据(JSON格式)
     */
    private String metadata;

    /**
     * 模型参数数据(JSON格式)
     */
    private String modelData;

    /**
     * 模型描述
     */
    private String description;

    /**
     * 标签(JSON数组字符串)
     */
    private String labels;

    /**
     * 随机种子
     */
    private Integer randomSeed;

    /**
     * 参数数量
     */
    private Integer parametersCount;

    /**
     * 模型校验和
     */
    private String checksum;

    /**
     * 模型文件存储路径
     */
    private String storagePath;

    /**
     * 状态: GENERATING, READY, DISTRIBUTED, FAILED
     */
    private InitialModelStatus status;

    /**
     * 绑定状态: UNBOUND / BOUND
     */
    private InitialModelBindingStatus bindingStatus;

    /**
     * 当前绑定模式（AUTO/CUSTOM），未绑定时为空
     */
    private GenerationMethod bindingMode;

    /**
     * 当前绑定是否由AUTO流程自动生成
     */
    private Boolean bindingAutoGenerated;

    /**
     * 最近绑定时间
     */
    private LocalDateTime boundAt;

    /**
     * 最近绑定操作人
     */
    private String boundBy;

    /**
     * 最近解绑时间
     */
    private LocalDateTime unboundAt;

    /**
     * 最近解绑操作人
     */
    private String unboundBy;

    /**
     * 是否由AUTO模式自动生成
     */
    private Boolean autoGenerated;

    /**
     * 创建时间
     */
    private LocalDateTime createdAt;

    /**
     * 创建者ID(32位UUID)
     */
    private String createdBy;

    /**
     * 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 更新者ID
     */
    private String updatedBy;
}
