package com.feduwacomm.vo;

import com.feduwacomm.model.vo.initial.InitialModelBindingVO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * 初始模型信息概要 VO
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InitialModelInfoVO {

    /**
     * 模型ID
     */
    private String modelId;

    /**
     * 模型类型
     */
    private String modelType;

    /**
     * 生成方式：AUTO / CUSTOM
     */
    private String generationMethod;

    /**
     * 模型大小（字节）
     */
    private Long modelSize;

    /**
     * 模型大小（格式化显示）
     */
    private String modelSizeFormatted;

    /**
     * 架构参数
     */
    private Map<String, Object> architecture;

    /**
     * 元数据（例如框架、版本等）
     */
    private Map<String, Object> metadata;

    /**
     * 标签列表
     */
    private List<String> labels;

    /**
     * 模型状态
     */
    private String status;

    /**
     * 状态描述
     */
    private String statusDescription;

    /**
     * 绑定状态：UNBOUND / BOUND
     */
    private String bindingStatus;

    /**
     * 是否自动生成
     */
    private Boolean autoGenerated;

    /**
     * 当前激活的绑定信息
     */
    private InitialModelBindingVO activeBinding;

    /**
     * 分发统计
     */
    private DistributionStats distributionStats;

    /**
     * 模型校验和
     */
    private String checksum;

    /**
     * 创建时间
     */
    private LocalDateTime createdAt;

    /**
     * 最近更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 分发状态统计
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DistributionStats {
        private Integer total;
        private Integer completed;
        private Integer inProgress;
        private Integer failed;
        private Double progressPercentage;
        private LocalDateTime latestDistributionAt;
    }

    /**
     * 模型生成统计
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ModelGenerationStats {
        private Integer totalModels;
        private Integer generating;
        private Integer ready;
        private Integer distributed;
        private Integer failed;
        private Double successRate;
        private Double avgGenerationTime;
    }
}
