package com.feduwacomm.dto;

public enum ProtocolType {
    CONNECT,
    CONNECT_ACK,
    HEARTBEAT,
    HEARTBEAT_ACK,

    VM_START,
    VM_STOP,

    TRAINING_START,
    TRAINING_START_ACK,
    TRAINING_START_RESPONSE,
    TRAINING_START_RESPONSE_ACK,
    TRAINING_STOP,
    TRAINING_STOP_ACK,
    TRAINING_PROGRESS,
    TRAINING_PROGRESS_ACK,
    TRAINING_PROGRESS_RESPONSE,
    TRAINING_PROGRESS_RESPONSE_ACK,

    MODEL_UPLOAD,
    MODEL_DOWNLOAD,
    GLOBAL_MODEL_UPDATE,

    STATUS_QUERY,
    STATUS_RESPONSE,
    BATCH_STATUS_QUERY,
    BATCH_STATUS_RESPONSE,

    ERROR,
    CONNECTION_ERROR,
    MESSAGE_ERROR,
    STATUS_QUERY_ERROR,

    DATASET_CREATE,
    DATASET_CREATE_ACK,
    DATASET_APPEND_ROWS,
    DATASET_APPEND_ROWS_ACK,
    DATASET_COMPLETE,
    DATASET_COMPLETE_ACK,
    DATASET_STATUS_QUERY,
    DATASET_STATUS_RESPONSE,
    DATASET_DELETE,
    DATASET_DELETE_ACK
} 