package com.feduwacomm.dto;

public enum ProtocolType {
    CONNECT,
    CONNECT_ACK,
    HEARTBEAT,
    HEARTBEAT_ACK,

    VM_START,
    VM_STOP,

    TRAINING_START,
    TRAINING_START_ACK,
    TRAINING_START_COMMAND,
    TRAINING_START_RESPONSE,
    TRAINING_START_RESPONSE_ACK,
    TRAINING_STOP,
    TRAINING_STOP_ACK,
    TRAINING_PROGRESS,
    TRAINING_PROGRESS_ACK,
    TRAINING_PROGRESS_RESPONSE,
    TRAINING_PROGRESS_RESPONSE_ACK,

    MODEL_UPLOAD,
    MODEL_DOWNLOAD,
    GLOBAL_MODEL_UPDATE,
    MODEL_UPDATE_ACK,

    TASK_START,
    TASK_START_ACK,
    FEDERATED_TASK_START,
    FEDERATED_TASK_START_ACK,

    STATUS_QUERY,
    STATUS_RESPONSE,
    BATCH_STATUS_QUERY,
    BATCH_STATUS_RESPONSE,

    ERROR,
    CONNECTION_ERROR,
    MESSAGE_ERROR,
    STATUS_QUERY_ERROR,

    DATASET_CREATE,
    DATASET_CREATE_ACK,
    DATASET_APPEND_ROWS,
    DATASET_APPEND_ROWS_ACK,
    DATASET_COMPLETE,
    DATASET_COMPLETE_ACK,
    DATASET_STATUS_QUERY,
    DATASET_STATUS_RESPONSE,
    DATASET_DELETE,
    DATASET_DELETE_ACK,

    // Business layer notification messages (v1.4 additions)
    // These notifications are sent by server to clients when corresponding operations complete
    DATASET_CREATE_NOTIFICATION,
    DATASET_APPEND_ROWS_NOTIFICATION,
    DATASET_COMPLETE_NOTIFICATION,
    TRAINING_START_COMMAND_NOTIFICATION,
    TRAINING_START_NOTIFICATION,
    TRAINING_START_FAILURE_NOTIFICATION,
    TRAINING_STOP_COMMAND_NOTIFICATION,
    TRAINING_PROGRESS_QUERY_NOTIFICATION,
    TRAINING_PROGRESS_UPDATE_NOTIFICATION,
    MODEL_DOWNLOAD_NOTIFICATION,
    STATUS_UPDATE_NOTIFICATION
} 