package com.feduwacomm.dto;

public enum ProtocolType {
    CONNECT,
    CONNECT_ACK,
    HEARTBEAT,
    HEARTBEAT_ACK,

    VM_START,
    VM_STOP,

    TRAINING_START,
    TRAINING_START_ACK,
    TRAINING_START_COMMAND,
    TRAINING_START_RESPONSE,
    TRAINING_START_RESPONSE_ACK,
    TRAINING_STOP,
    TRAINING_STOP_ACK,
    TRAINING_PROGRESS,
    TRAINING_PROGRESS_ACK,
    TRAINING_PROGRESS_RESPONSE,
    TRAINING_PROGRESS_RESPONSE_ACK,

    MODEL_UPLOAD,
    MODEL_UPLOAD_ACK,
    MODEL_DOWNLOAD,
    MODEL_DOWNLOAD_ACK,
    GLOBAL_MODEL_UPDATE,
    GLOBAL_MODEL_UPDATE_ACK,
    MODEL_UPDATE_ACK,

    // 联邦学习聚合消息
    GRADIENT_UPLOAD,
    GRADIENT_UPLOAD_ACK,
    GLOBAL_MODEL_BROADCAST,
    GLOBAL_MODEL_BROADCAST_ACK,
    AGGREGATION_START,
    AGGREGATION_START_ACK,
    AGGREGATION_COMPLETE,
    AGGREGATION_COMPLETE_ACK,
    ROUND_START,
    ROUND_START_ACK,
    ROUND_COMPLETE,
    ROUND_COMPLETE_ACK,

    TASK_START,
    TASK_START_ACK,
    FEDERATED_TASK_START,
    FEDERATED_TASK_START_ACK,

    STATUS_QUERY,
    STATUS_RESPONSE,
    BATCH_STATUS_QUERY,
    BATCH_STATUS_RESPONSE,

    ERROR,
    CONNECTION_ERROR,
    MESSAGE_ERROR,
    STATUS_QUERY_ERROR,

    DATASET_CREATE,
    DATASET_CREATE_ACK,
    DATASET_APPEND_ROWS,
    DATASET_APPEND_ROWS_ACK,
    DATASET_COMPLETE,
    DATASET_COMPLETE_ACK,
    DATASET_STATUS_QUERY,
    DATASET_STATUS_RESPONSE,
    DATASET_DELETE,
    DATASET_DELETE_ACK,

    // 联邦学习增强协议 (v1.4版本新增)
    MODEL_TYPE_NEGOTIATION,
    MODEL_TYPE_NEGOTIATION_ACK,
    ALGORITHM_CONFIG,
    ALGORITHM_CONFIG_ACK,
    GRADIENT_UPLOAD_PREPARE,
    GRADIENT_UPLOAD_PREPARE_ACK,
    AGGREGATION_NOTIFICATION,
    STRATEGY_SWITCH_NOTIFICATION,
    STRATEGY_SWITCH_ACK,

    // 服务端广播消息类型 (v1.4版本新增)
    GLOBAL_MODEL_BROADCAST_NOTIFICATION,
    AGGREGATION_START_NOTIFICATION,
    AGGREGATION_COMPLETE_NOTIFICATION,
    ROUND_START_NOTIFICATION,
    ROUND_COMPLETE_NOTIFICATION,


    // 业务层通知消息 (v1.4版本新增)
    // 这些通知消息由服务端主动推送给客户端，表明对应操作已完成
    DATASET_CREATE_NOTIFICATION,
    DATASET_APPEND_ROWS_NOTIFICATION,
    DATASET_COMPLETE_NOTIFICATION,
    TRAINING_START_COMMAND_NOTIFICATION,
    TRAINING_START_NOTIFICATION,
    TRAINING_START_FAILURE_NOTIFICATION,
    TRAINING_STOP_COMMAND_NOTIFICATION,
    TRAINING_PROGRESS_QUERY_NOTIFICATION,
    TRAINING_PROGRESS_UPDATE_NOTIFICATION,
    MODEL_DOWNLOAD_NOTIFICATION,
    STATUS_UPDATE_NOTIFICATION
} 