package com.feduwacomm.model.vo.initial;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 初始模型绑定记录视图对象
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InitialModelBindingVO {

    /**
     * 初始模型ID
     */
    private String modelId;

    /**
     * 绑定任务ID
     */
    private String taskId;

    /**
     * 绑定任务名称
     */
    private String taskName;

    /**
     * 绑定模式：AUTO / CUSTOM
     */
    private String mode;

    /**
     * 绑定状态：BOUND / UNBOUND
     */
    private String status;

    /**
     * 是否由AUTO模式自动生成
     */
    private Boolean autoGenerated;

    /**
     * 绑定时间
     */
    private LocalDateTime boundAt;

    /**
     * 解绑时间
     */
    private LocalDateTime unboundAt;

    /**
     * 绑定操作人
     */
    private String boundBy;

    /**
     * 解绑操作人
     */
    private String unboundBy;
}
