package com.feduwacomm.model.vo.initial;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * 初始模型详情视图对象
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InitialModelDetailVO {

    private String modelId;
    private String modelType;
    private String generationMethod;
    private Long modelSize;
    private String modelSizeFormatted;
    private Map<String, Object> architecture;
    private Map<String, Object> metadata;
    private List<String> labels;
    private String description;
    private Integer randomSeed;
    private Integer parametersCount;
    private Map<String, Object> modelParameters;
    private String checksum;
    private String storagePath;
    private String status;
    private String statusDescription;
    private Boolean autoGenerated;
    private String bindingStatus;
    private InitialModelBindingVO activeBinding;
    private List<InitialModelBindingVO> bindings;
    private DistributionStats distributionStats;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime updatedAt;
    private String updatedBy;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DistributionStats {
        private Integer total;
        private Integer completed;
        private Integer inProgress;
        private Integer failed;
        private Double progressPercentage;
        private LocalDateTime latestDistributionAt;
    }
}
